In [1]:
import os
from pprint import pprint

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
)
from sklearn.model_selection import train_test_split
from tqdm import tqdm
import numpy as np
import pandas as pd
import sklearn
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, OneHotEncoder

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.linear_model import LogisticRegression,RidgeClassifier

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, BaggingClassifier, VotingClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import SVC

import xgboost as xgb
from xgboost import XGBClassifier
from xgboost import plot_importance

import lightgbm as lgb
from lightgbm import LGBMClassifier
from lightgbm import plot_importance

import catboost
from catboost import CatBoostClassifier

from lightgbm import LGBMClassifier
import lightgbm as lgb
from sklearn.model_selection import train_test_split as tts
from bayes_opt import BayesianOptimization
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score, KFold
from sklearn.metrics import log_loss

from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import f1_score, roc_auc_score
from imblearn.over_sampling import RandomOverSampler, SMOTE, ADASYN, BorderlineSMOTE
import random
import os

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
)

import os
import warnings
import pandas as pd
import xgboost as xgb
import matplotlib.pyplot as plt

os.environ['KMP_DUPLICATE_LIB_OK']='True'
warnings.filterwarnings("ignore", category=FutureWarning)

In [2]:
def get_clf_eval(y_test, y_pred=None):
    confusion = confusion_matrix(y_test, y_pred, labels=[0, 1])
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, labels=[0, 1])
    recall = recall_score(y_test, y_pred)
    F1 = f1_score(y_test, y_pred, labels=[0, 1])

    print("오차행렬:\n", confusion)
    print("\n정확도: {:.4f}".format(accuracy))
    print("정밀도: {:.4f}".format(precision))
    print("재현율: {:.4f}".format(recall))
    print("F1: {:.4f}".format(F1))

In [3]:
train = pd.read_csv('최종train.csv')
test = pd.read_csv('최종test.csv')

In [4]:
X = train[train.columns.drop('target')]
Y = train['target']
# X와 Y로 나누기
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42, shuffle=True)
# 양성 클래스와 음성 클래스의 비율 계산
ratio = float(np.sum(y_train == 0)) / np.sum(y_train == 1)
# ratio
test_index_0 = [   64,   562,  1460,  1530,  1892,  2505,  2710,  3457,  3682,
             3732,  4928,  4932,  6092,  7001,  7287,  7666,  7836,  8253,
             8898, 10989, 12439, 12585, 12844, 14756, 15180, 15406, 15811,
            15964]

xgb pre, xgb f1, lgbm f1, cat pre, cat f1, ext pre, ext f1, ext pre 2, ext f1 2, rf pre, rf f1

In [5]:
xg_0830_pre =  {'scale_pos_weight': 7.341320339056038, 'n_estimators': 388, 'alpha': 1.0721670498752341e-05, 'gamma': 6.068658665488514e-05, 'learning_rate': 0.12026975972095454, 'max_depth': 11}
model_xgb_pre = xgb.XGBClassifier(random_state=42,
                              scale_pos_weight=xg_0830_pre['scale_pos_weight'],
                              max_depth = xg_0830_pre['max_depth'],
                              n_estimators= xg_0830_pre['n_estimators'],
                              alpha = xg_0830_pre['alpha'],
                              gamma = xg_0830_pre['gamma'],
                              learning_rate = xg_0830_pre['learning_rate'],
                             ) 

model_xgb_pre.fit(X_train, y_train)
y_pred_xgb = model_xgb_pre.predict(X_test)

print('\n\033[95mxgb pre\033[0m')
accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
print(f"XGBoost Accuracy: {accuracy_xgb}")
print(f1_score(y_test, y_pred_xgb, average='binary'))
pred_xgb = model_xgb_pre.predict(X_test.fillna(0))
get_clf_eval(y_test, pred_xgb)
# 예측에 필요한 데이터 분리
x_test = test.drop(["target"], axis=1)
test_pred_xgb = model_xgb_pre.predict(x_test.drop(['Set ID'],axis = 1))
# sum(test_pred) # True로 예측된 개수
print(np.unique(test_pred_xgb,return_counts = True))
test_pred_labels_xgb = np.where(test_pred_xgb == 1, 'AbNormal', 'Normal')
print(np.unique(test_pred_labels_xgb,return_counts = True))
print(np.unique(test_pred_labels_xgb[test_index_0],return_counts = True))
#제출 데이터 읽어오기 (df_test는 전처리된 데이터가 저장됨)
df_sub_xgb_pre = pd.read_csv("submission.csv")
df_sub_xgb_pre["target"] = test_pred_labels_xgb
df_sub_xgb_pre.loc[test_index_0 , 'target'] = 'AbNormal'
# df_sub.loc[test_index_1 , 'target'] = test_pred_labels
print(np.unique(df_sub_xgb_pre['target'],return_counts = True))
print(np.unique(df_sub_xgb_pre['target'],return_counts = True)[1][0]/np.unique(df_sub_xgb_pre['target'],return_counts = True)[1][1])
index = [181,498,679,1510,1739,3055, 3687, 4618, 5311, 5702, 5886, 7075, 8354, 8414, 8898, 9043, 10188, 10191, 10345, 10424,10948, 14807, 15456, 16876]
print(np.unique(df_sub_xgb_pre.loc[index, 'target'],return_counts= True))
df_sub_xgb_pre.loc[index, 'target'] = 'AbNormal'
print(np.unique(df_sub_xgb_pre['target'],return_counts = True))


print('\n\033[95mxgb f1\033[0m')
xgb_f1_0830 = {'scale_pos_weight': 8.39217381852957, 'n_estimators': 446, 'alpha': 0.0004293988100794859, 'gamma': 4.289625215767432e-06, 'learning_rate': 0.013484331238330214, 'max_depth': 3}
model_xgb_f1 = xgb.XGBClassifier(random_state=42,
                              scale_pos_weight=xgb_f1_0830['scale_pos_weight'],
                              max_depth = xgb_f1_0830['max_depth'],
                              n_estimators= xgb_f1_0830['n_estimators'],
                              alpha = xgb_f1_0830['alpha'],
                              gamma = xgb_f1_0830['gamma'],
                              learning_rate = xgb_f1_0830['learning_rate'],
                             ) 

model_xgb_f1.fit(X_train, y_train)
y_pred_xgb = model_xgb_f1.predict(X_test)

accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
print(f"XGBoost Accuracy: {accuracy_xgb}")
print(f1_score(y_test, y_pred_xgb, average='binary'))
pred_xgb = model_xgb_f1.predict(X_test.fillna(0))
get_clf_eval(y_test, pred_xgb)
# 예측에 필요한 데이터 분리
x_test = test.drop(["target"], axis=1)
test_pred_xgb = model_xgb_f1.predict(x_test.drop(['Set ID'],axis = 1))
# sum(test_pred) # True로 예측된 개수
print(np.unique(test_pred_xgb,return_counts = True))
test_pred_labels_xgb = np.where(test_pred_xgb == 1, 'AbNormal', 'Normal')
print(np.unique(test_pred_labels_xgb,return_counts = True))
print(np.unique(test_pred_labels_xgb[test_index_0],return_counts = True))
#제출 데이터 읽어오기 (df_test는 전처리된 데이터가 저장됨)
df_sub_xgb_f1 = pd.read_csv("submission.csv")
df_sub_xgb_f1["target"] = test_pred_labels_xgb
df_sub_xgb_f1.loc[test_index_0 , 'target'] = 'AbNormal'
# df_sub.loc[test_index_1 , 'target'] = test_pred_labels
print(np.unique(df_sub_xgb_f1['target'],return_counts = True))
print(np.unique(df_sub_xgb_f1['target'],return_counts = True)[1][0]/np.unique(df_sub_xgb_f1['target'],return_counts = True)[1][1])
index = [181,498,679,1510,1739,3055, 3687, 4618, 5311, 5702, 5886, 7075, 8354, 8414, 8898, 9043, 10188, 10191, 10345, 10424,10948, 14807, 15456, 16876]
print(np.unique(df_sub_xgb_f1.loc[index, 'target'],return_counts= True))
df_sub_xgb_f1.loc[index, 'target'] = 'AbNormal'
print(np.unique(df_sub_xgb_f1['target'],return_counts = True))



print('\n\033[95mlgbm f1\033[0m')
f1_lgbm = {'n_estimators': 75, 'learning_rate': 0.024289232165634188, 'num_leaves': 88, 'max_depth': 5, 'scale_pos_weight': 12.258711848102562}
from lightgbm import LGBMClassifier
# LightGBM 모델 생성
model_lgbm_f1 = LGBMClassifier(
    random_state=42,
    n_estimators=f1_lgbm['n_estimators'],
    learning_rate= f1_lgbm['learning_rate'],
    num_leaves=f1_lgbm['num_leaves'],
    max_depth=f1_lgbm['max_depth'],
    scale_pos_weight = f1_lgbm['scale_pos_weight']
)
                            
               
# 모델 학습
model_lgbm_f1.fit(X_train, y_train)

# 예측
y_pred_lgbm = model_lgbm_f1.predict(X_test)

# 정확도 및 F1 점수 계산
accuracy_lgbm = accuracy_score(y_test, y_pred_lgbm)
print(f"LGBM Accuracy: {accuracy_lgbm}")
print(f1_score(y_test, y_pred_lgbm, average='binary'))
pred_lgbm = model_lgbm_f1.predict(X_test.fillna(0))
get_clf_eval(y_test, pred_lgbm)
print(np.unique(y_test,return_counts = True))
# 예측에 필요한 데이터 분리
x_test = test.drop(["target"], axis=1)
test_pred_lgbm = model_lgbm_f1.predict(x_test.drop(['Set ID'],axis = 1))
# sum(test_pred) # True로 예측된 개수
print(np.unique(test_pred_lgbm,return_counts = True))
test_pred_labels_lgbm = np.where(test_pred_lgbm == 1, 'AbNormal', 'Normal')
print(np.unique(test_pred_labels_lgbm,return_counts = True))
print(np.unique(test_pred_labels_lgbm[test_index_0],return_counts = True))
#제출 데이터 읽어오기 (df_test는 전처리된 데이터가 저장됨)
df_sub_lgbm_f1 = pd.read_csv("submission.csv")
df_sub_lgbm_f1["target"] = test_pred_labels_lgbm
df_sub_lgbm_f1.loc[test_index_0 , 'target'] = 'AbNormal'
# df_sub.loc[test_index_1 , 'target'] = test_pred_labels
print(np.unique(df_sub_lgbm_f1['target'],return_counts = True))
print(np.unique(df_sub_lgbm_f1['target'],return_counts = True)[1][0]/np.unique(df_sub_lgbm_f1['target'],return_counts = True)[1][1])
index = [181,498,679,1510,1739,3055, 3687, 4618, 5311, 5702, 5886, 7075, 8354, 8414, 8898, 9043, 10188, 10191, 10345, 10424,10948, 14807, 15456, 16876]
print(np.unique(df_sub_lgbm_f1.loc[index, 'target'],return_counts= True))
df_sub_lgbm_f1.loc[index, 'target'] = 'AbNormal'
print(np.unique(df_sub_lgbm_f1['target'],return_counts = True))


print('\n\033[95mcat f1\033[0m')
Best_trial_cat_f1 = {'iterations': 339, 'learning_rate': 0.015504002784165248, 'depth': 6, 'scale_pos_weight': 8.711700270466679, 'random_state': 28}
from catboost import CatBoostClassifier

# CatBoost 모델 생성
model_catboost_f1 = CatBoostClassifier(
    random_state=Best_trial_cat_f1['random_state'],
    iterations=Best_trial_cat_f1['iterations'], # n_estimators와 비슷합니다.
    learning_rate=Best_trial_cat_f1['learning_rate'],
    depth=Best_trial_cat_f1['depth'], # max_depth와 비슷합니다.
    scale_pos_weight=Best_trial_cat_f1['scale_pos_weight'], # max_depth와 비슷합니다.
    silent=True, # 학습 과정에서 메시지를 출력하지 않습니다.
    thread_count = -1
)

# 모델 학습
model_catboost_f1.fit(X_train, y_train)
# 예측
y_pred_catboost = model_catboost_f1.predict(X_test)

# 정확도 및 F1 점수 계산
accuracy_catboost = accuracy_score(y_test, y_pred_catboost)
print(f"CatBoost Accuracy: {accuracy_catboost}")
print(f1_score(y_test, y_pred_catboost, average='binary'))
pred_cat = model_catboost_f1.predict(X_test.fillna(0))
get_clf_eval(y_test, pred_cat)
# 예측에 필요한 데이터 분리
x_test = test.drop(["target"], axis=1)
test_pred_cat = model_catboost_f1.predict(x_test.drop(['Set ID'],axis = 1))
# sum(test_pred) # True로 예측된 개수
print(np.unique(test_pred_cat,return_counts = True))
test_pred_labels_cat = np.where(test_pred_cat == 1, 'AbNormal', 'Normal')
print(np.unique(test_pred_labels_cat,return_counts = True))
print(np.unique(test_pred_labels_cat[test_index_0],return_counts = True))
#제출 데이터 읽어오기 (df_test는 전처리된 데이터가 저장됨)
df_sub_cat_f1 = pd.read_csv("submission.csv")
df_sub_cat_f1["target"] = test_pred_labels_cat
df_sub_cat_f1.loc[test_index_0 , 'target'] = 'AbNormal'
# df_sub.loc[test_index_1 , 'target'] = test_pred_labels
print(np.unique(df_sub_cat_f1['target'],return_counts = True))
print(np.unique(df_sub_cat_f1['target'],return_counts = True)[1][0]/np.unique(df_sub_cat_f1['target'],return_counts = True)[1][1])
index = [181,498,679,1510,1739,3055, 3687, 4618, 5311, 5702, 5886, 7075, 8354, 8414, 8898, 9043, 10188, 10191, 10345, 10424,10948, 14807, 15456, 16876]
print(np.unique(df_sub_cat_f1.loc[index, 'target'],return_counts= True))
df_sub_cat_f1.loc[index, 'target'] = 'AbNormal'
print(np.unique(df_sub_cat_f1['target'],return_counts = True))


print('\n\033[95mcat pre\033[0m')
cat_0828_pre_try3 = {'iterations': 477, 'learning_rate': 0.21149532084747522, 'depth': 9, 'scale_pos_weight': 7.182149667387197, 'random_state': 1}
from catboost import CatBoostClassifier

# CatBoost 모델 생성
model_catboost_pre = CatBoostClassifier(
    random_state=cat_0828_pre_try3['random_state'],
    iterations=cat_0828_pre_try3['iterations'], # n_estimators와 비슷합니다.
    learning_rate=cat_0828_pre_try3['learning_rate'],
    depth=cat_0828_pre_try3['depth'], # max_depth와 비슷합니다.
    scale_pos_weight=cat_0828_pre_try3['scale_pos_weight'], # max_depth와 비슷합니다.
    silent=True, # 학습 과정에서 메시지를 출력하지 않습니다.
    thread_count = -1
)

# 모델 학습
model_catboost_pre.fit(X_train, y_train)
# 예측
y_pred_catboost = model_catboost_pre.predict(X_test)

# 정확도 및 F1 점수 계산
accuracy_catboost = accuracy_score(y_test, y_pred_catboost)
print(f"CatBoost Accuracy: {accuracy_catboost}")
print(f1_score(y_test, y_pred_catboost, average='binary'))
pred_cat = model_catboost_pre.predict(X_test.fillna(0))
get_clf_eval(y_test, pred_cat)
# 예측에 필요한 데이터 분리
x_test = test.drop(["target"], axis=1)
test_pred_cat = model_catboost_pre.predict(x_test.drop(['Set ID'],axis = 1))
# sum(test_pred) # True로 예측된 개수
print(np.unique(test_pred_cat,return_counts = True))
test_pred_labels_cat = np.where(test_pred_cat == 1, 'AbNormal', 'Normal')
print(np.unique(test_pred_labels_cat,return_counts = True))
print(np.unique(test_pred_labels_cat[test_index_0],return_counts = True))
#제출 데이터 읽어오기 (df_test는 전처리된 데이터가 저장됨)
df_sub_cat_pre = pd.read_csv("submission.csv")
df_sub_cat_pre["target"] = test_pred_labels_cat
df_sub_cat_pre.loc[test_index_0 , 'target'] = 'AbNormal'
# df_sub.loc[test_index_1 , 'target'] = test_pred_labels
print(np.unique(df_sub_cat_pre['target'],return_counts = True))
print(np.unique(df_sub_cat_pre['target'],return_counts = True)[1][0]/np.unique(df_sub_cat_pre['target'],return_counts = True)[1][1])
index = [181,498,679,1510,1739,3055, 3687, 4618, 5311, 5702, 5886, 7075, 8354, 8414, 8898, 9043, 10188, 10191, 10345, 10424,10948, 14807, 15456, 16876]
print(np.unique(df_sub_cat_pre.loc[index, 'target'],return_counts= True))
df_sub_cat_pre.loc[index, 'target'] = 'AbNormal'
print(np.unique(df_sub_cat_pre['target'],return_counts = True))


print('\n\033[95mext f1 ver1\033[0m')
from sklearn.ensemble import ExtraTreesClassifier
f1_0828_try3_extratree =  {'n_estimators': 102, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 0.9826117414545161, 'class_weight_0': 1.457568770147802, 'class_weight_1': 14.272785578442846}
model_extratree_f1 = ExtraTreesClassifier(
    random_state=42,
#     class_weight = 'balanced',
    class_weight = {0:f1_0828_try3_extratree['class_weight_0'],1:f1_0828_try3_extratree['class_weight_1']},
    n_jobs = -1,
    n_estimators = f1_0828_try3_extratree['n_estimators'],
    max_depth = f1_0828_try3_extratree['max_depth'],
    min_samples_split = f1_0828_try3_extratree['min_samples_split'],
    min_samples_leaf = f1_0828_try3_extratree['min_samples_leaf'],
    
    max_features = f1_0828_try3_extratree['max_features']
)
# 모델 학습
model_extratree_f1.fit(X_train, y_train)
# 예측
y_pred_extratree = model_extratree_f1.predict(X_test)

# 정확도 및 F1 점수 계산
accuracy_extratree = accuracy_score(y_test, y_pred_extratree)
print(f"extratree Accuracy: {accuracy_extratree}")
print(f1_score(y_test, y_pred_extratree, average='binary'))
pred_ext = model_extratree_f1.predict(X_test.fillna(0))
get_clf_eval(y_test, pred_ext)
# 예측에 필요한 데이터 분리
x_test = test.drop(["target"], axis=1)
test_pred_ext = model_extratree_f1.predict(x_test.drop(['Set ID'],axis = 1))
# sum(test_pred) # True로 예측된 개수
print(np.unique(test_pred_ext,return_counts = True))
test_pred_labels_ext = np.where(test_pred_ext == 1, 'AbNormal', 'Normal')
print(np.unique(test_pred_labels_ext,return_counts = True))
print(np.unique(test_pred_labels_ext[test_index_0],return_counts = True))
#제출 데이터 읽어오기 (df_test는 전처리된 데이터가 저장됨)
df_sub_ext_f1_ver1 = pd.read_csv("submission.csv")
df_sub_ext_f1_ver1["target"] = test_pred_labels_ext
df_sub_ext_f1_ver1.loc[test_index_0 , 'target'] = 'AbNormal'
# df_sub.loc[test_index_1 , 'target'] = test_pred_labels
print(np.unique(df_sub_ext_f1_ver1['target'],return_counts = True))
print(np.unique(df_sub_ext_f1_ver1['target'],return_counts = True)[1][0]/np.unique(df_sub_ext_f1_ver1['target'],return_counts = True)[1][1])
index = [181,498,679,1510,1739,3055, 3687, 4618, 5311, 5702, 5886, 7075, 8354, 8414, 8898, 9043, 10188, 10191, 10345, 10424,10948, 14807, 15456, 16876]
print(np.unique(df_sub_ext_f1_ver1.loc[index, 'target'],return_counts= True))
df_sub_ext_f1_ver1.loc[index,'target'] = 'AbNormal'
print(np.unique(df_sub_ext_f1_ver1['target'],return_counts = True))
# df_sub_ext.to_csv('submission.csv',index = False)


print('\n\033[95mext f1 ver2\033[0m')
ext_f12 =  {'n_estimators': 444, 'max_depth': 4, 'min_samples_split': 9, 'min_samples_leaf': 9, 'max_features': 0.6885880051558815, 'class_weight_0': 1.5849604964318942, 'class_weight_1': 15.669554473639145}
model_extratree_f1_ver2 = ExtraTreesClassifier(
    random_state=42,
#     class_weight = 'balanced',
    class_weight = {0:ext_f12['class_weight_0'],1:ext_f12['class_weight_1']},
    n_jobs = -1,
    n_estimators = ext_f12['n_estimators'],
    max_depth = ext_f12['max_depth'],
    min_samples_split = ext_f12['min_samples_split'],
    min_samples_leaf = ext_f12['min_samples_leaf'],
    
    max_features = ext_f12['max_features']
)
# 모델 학습
model_extratree_f1_ver2.fit(X_train, y_train)
# 예측
y_pred_extratree = model_extratree_f1_ver2.predict(X_test)

# 정확도 및 F1 점수 계산
accuracy_extratree = accuracy_score(y_test, y_pred_extratree)
print(f"extratree Accuracy: {accuracy_extratree}")
print(f1_score(y_test, y_pred_extratree, average='binary'))
pred_ext = model_extratree_f1_ver2.predict(X_test.fillna(0))
get_clf_eval(y_test, pred_ext)
# 예측에 필요한 데이터 분리
x_test = test.drop(["target"], axis=1)
test_pred_ext = model_extratree_f1_ver2.predict(x_test.drop(['Set ID'],axis = 1))
# sum(test_pred) # True로 예측된 개수
print(np.unique(test_pred_ext,return_counts = True))
test_pred_labels_ext = np.where(test_pred_ext == 1, 'AbNormal', 'Normal')
print(np.unique(test_pred_labels_ext,return_counts = True))
print(np.unique(test_pred_labels_ext[test_index_0],return_counts = True))
#제출 데이터 읽어오기 (df_test는 전처리된 데이터가 저장됨)
df_sub_ext_f1_ver2 = pd.read_csv("submission.csv")
df_sub_ext_f1_ver2["target"] = test_pred_labels_ext
df_sub_ext_f1_ver2.loc[test_index_0 , 'target'] = 'AbNormal'
# df_sub.loc[test_index_1 , 'target'] = test_pred_labels
print(np.unique(df_sub_ext_f1_ver2['target'],return_counts = True))
print(np.unique(df_sub_ext_f1_ver2['target'],return_counts = True)[1][0]/np.unique(df_sub_ext_f1_ver2['target'],return_counts = True)[1][1])
index = [181,498,679,1510,1739,3055, 3687, 4618, 5311, 5702, 5886, 7075, 8354, 8414, 8898, 9043, 10188, 10191, 10345, 10424,10948, 14807, 15456, 16876]
print(np.unique(df_sub_ext_f1_ver2.loc[index, 'target'],return_counts= True))
df_sub_ext_f1_ver2.loc[index,'target'] = 'AbNormal'
print(np.unique(df_sub_ext_f1_ver2['target'],return_counts = True))
# df_sub_ext.to_csv('submission.csv',index = False)

print('\n\033[95mext pre ver1\033[0m')
pre_ext_0830 =  {'n_estimators': 189, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': 0.9669827142989229, 'class_weight_0': 1.5012439030311733, 'class_weight_1': 4.044000824919951}
from sklearn.ensemble import ExtraTreesClassifier


model_extratree_pre = ExtraTreesClassifier(
    random_state=42,
    class_weight = {0:pre_ext_0830['class_weight_0'],1:pre_ext_0830['class_weight_1']},
    n_estimators = pre_ext_0830['n_estimators'],
    max_depth = pre_ext_0830['max_depth'],
    min_samples_split = pre_ext_0830['min_samples_split'],
    min_samples_leaf = pre_ext_0830['min_samples_leaf'],
    n_jobs = -1,
    max_features = pre_ext_0830['max_features']
)
# 모델 학습
model_extratree_pre.fit(X_train, y_train)
# 예측
y_pred_extratree = model_extratree_pre.predict(X_test)

# 정확도 및 F1 점수 계산
accuracy_extratree = accuracy_score(y_test, y_pred_extratree)
print(f"extratree Accuracy: {accuracy_extratree}")
print(f1_score(y_test, y_pred_extratree, average='binary'))
pred_ext = model_extratree_pre.predict(X_test.fillna(0))
get_clf_eval(y_test, pred_ext)
# 예측에 필요한 데이터 분리
x_test = test.drop(["target"], axis=1)
test_pred_ext = model_extratree_pre.predict(x_test.drop(['Set ID'],axis = 1))
# sum(test_pred) # True로 예측된 개수
print(np.unique(test_pred_ext,return_counts = True))
test_pred_labels_ext = np.where(test_pred_ext == 1, 'AbNormal', 'Normal')
print(np.unique(test_pred_labels_ext,return_counts = True))
print(np.unique(test_pred_labels_ext[test_index_0],return_counts = True))
#제출 데이터 읽어오기 (df_test는 전처리된 데이터가 저장됨)
df_sub_ext_pre_ver1 = pd.read_csv("submission.csv")
df_sub_ext_pre_ver1["target"] = test_pred_labels_ext
df_sub_ext_pre_ver1.loc[test_index_0 , 'target'] = 'AbNormal'
# df_sub.loc[test_index_1 , 'target'] = test_pred_labels
print(np.unique(df_sub_ext_pre_ver1['target'],return_counts = True))
print(np.unique(df_sub_ext_pre_ver1['target'],return_counts = True)[1][0]/np.unique(df_sub_ext_pre_ver1['target'],return_counts = True)[1][1])
index = [181,498,679,1510,1739,3055, 3687, 4618, 5311, 5702, 5886, 7075, 8354, 8414, 8898, 9043, 10188, 10191, 10345, 10424,10948, 14807, 15456, 16876]
print(np.unique(df_sub_ext_pre_ver1.loc[index, 'target'],return_counts= True))
df_sub_ext_pre_ver1.loc[index,'target'] = 'AbNormal'
print(np.unique(df_sub_ext_pre_ver1['target'],return_counts = True))


print('\n\033[95mext pre ver2\033[0m')
pre_ext_ver2_0830 =  {'n_estimators': 273, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 0.5026218482946515, 'class_weight_0': 1.6843391565220673, 'class_weight_1': 3.6976004251340204}
from sklearn.ensemble import ExtraTreesClassifier


model_extratree_pre_ver2 = ExtraTreesClassifier(
    random_state=42,
    class_weight = {0:pre_ext_ver2_0830['class_weight_0'],1:pre_ext_ver2_0830['class_weight_1']},
    n_estimators = pre_ext_ver2_0830['n_estimators'],
    max_depth = pre_ext_ver2_0830['max_depth'],
    min_samples_split = pre_ext_ver2_0830['min_samples_split'],
    min_samples_leaf = pre_ext_ver2_0830['min_samples_leaf'],
    n_jobs = -1,
    max_features = pre_ext_ver2_0830['max_features']
)
# 모델 학습
model_extratree_pre_ver2.fit(X_train, y_train)
# 예측
y_pred_extratree = model_extratree_pre_ver2.predict(X_test)

# 정확도 및 F1 점수 계산
accuracy_extratree = accuracy_score(y_test, y_pred_extratree)
print(f"extratree Accuracy: {accuracy_extratree}")
print(f1_score(y_test, y_pred_extratree, average='binary'))
pred_ext = model_extratree_pre_ver2.predict(X_test.fillna(0))
get_clf_eval(y_test, pred_ext)
# 예측에 필요한 데이터 분리
x_test = test.drop(["target"], axis=1)
test_pred_ext = model_extratree_pre_ver2.predict(x_test.drop(['Set ID'],axis = 1))
# sum(test_pred) # True로 예측된 개수
print(np.unique(test_pred_ext,return_counts = True))
test_pred_labels_ext = np.where(test_pred_ext == 1, 'AbNormal', 'Normal')
print(np.unique(test_pred_labels_ext,return_counts = True))
print(np.unique(test_pred_labels_ext[test_index_0],return_counts = True))
#제출 데이터 읽어오기 (df_test는 전처리된 데이터가 저장됨)
df_sub_ext_pre_ver2 = pd.read_csv("submission.csv")
df_sub_ext_pre_ver2["target"] = test_pred_labels_ext
df_sub_ext_pre_ver2.loc[test_index_0 , 'target'] = 'AbNormal'
# df_sub.loc[test_index_1 , 'target'] = test_pred_labels
print(np.unique(df_sub_ext_pre_ver2['target'],return_counts = True))
print(np.unique(df_sub_ext_pre_ver2['target'],return_counts = True)[1][0]/np.unique(df_sub_ext_pre_ver2['target'],return_counts = True)[1][1])
index = [181,498,679,1510,1739,3055, 3687, 4618, 5311, 5702, 5886, 7075, 8354, 8414, 8898, 9043, 10188, 10191, 10345, 10424,10948, 14807, 15456, 16876]
print(np.unique(df_sub_ext_pre_ver2.loc[index, 'target'],return_counts= True))
df_sub_ext_pre_ver2.loc[index,'target'] = 'AbNormal'


print('\n\033[95mrf pre\033[0m')
pre_0830 = {'n_estimators': 327, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_features': 0.6542410261825937, 'bootstrap': True, 'class_weight_0': 1.956487132576605, 'class_weight_1': 5.332973181680059}
model_rf_pre = RandomForestClassifier(
    random_state=42,
    class_weight = {0:pre_0830['class_weight_0'],1:pre_0830['class_weight_1']},
    n_estimators = pre_0830['n_estimators'],
    n_jobs = -1,
    max_depth = pre_0830['max_depth'],
    min_samples_split = pre_0830['min_samples_split'],
    min_samples_leaf =pre_0830['min_samples_leaf'] ,
    max_features = pre_0830['max_features'],
    bootstrap = pre_0830['bootstrap'],
    
)
# 모델 학습
model_rf_pre.fit(X_train, y_train)
# 예측
y_pred_rf = model_rf_pre.predict(X_test)

# 정확도 및 F1 점수 계산
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print(f"rf Accuracy: {accuracy_rf}")
print(f1_score(y_test, y_pred_rf, average='binary'))
pred_rf = model_rf_pre.predict(X_test.fillna(0))
get_clf_eval(y_test, pred_rf)
# 예측에 필요한 데이터 분리
x_test = test.drop(["target"], axis=1)
test_pred_rf = model_rf_pre.predict(x_test.drop(['Set ID'],axis = 1))
# sum(test_pred) # True로 예측된 개수
print(np.unique(test_pred_rf,return_counts = True))
test_pred_labels_rf = np.where(test_pred_rf == 1, 'AbNormal', 'Normal')
print(np.unique(test_pred_labels_rf,return_counts = True))
print(np.unique(test_pred_labels_rf[test_index_0],return_counts = True))
#제출 데이터 읽어오기 (df_test는 전처리된 데이터가 저장됨)
df_sub_rf_pre = pd.read_csv("submission.csv")
df_sub_rf_pre["target"] = test_pred_labels_rf
df_sub_rf_pre.loc[test_index_0 , 'target'] = 'AbNormal'
# df_sub.loc[test_index_1 , 'target'] = test_pred_labels
print(np.unique(df_sub_rf_pre['target'],return_counts = True))
print(np.unique(df_sub_rf_pre['target'],return_counts = True)[1][0]/np.unique(df_sub_rf_pre['target'],return_counts = True)[1][1])
index = [181,498,679,1510,1739,3055, 3687, 4618, 5311, 5702, 5886, 7075, 8354, 8414, 8898, 9043, 10188, 10191, 10345, 10424,10948, 14807, 15456, 16876]
print(np.unique(df_sub_rf_pre.loc[index, 'target'],return_counts= True))
df_sub_rf_pre.loc[index,'target'] = 'AbNormal'
print(np.unique(df_sub_rf_pre['target'],return_counts = True))


print('\n\033[95mrf f1\033[0m')
f1_tree_0830 =  {'n_estimators': 192, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 8, 'max_features': 0.3389310222483065, 'bootstrap': False, 'class_weight_0': 1.5148282373442297, 'class_weight_1': 14.094251957858043}
model_rf_f1 = RandomForestClassifier(
    random_state=42,
    class_weight = {0:f1_tree_0830['class_weight_0'],1:f1_tree_0830['class_weight_1']},
    n_estimators = f1_tree_0830['n_estimators'],
    n_jobs = -1,
    max_depth = f1_tree_0830['max_depth'],
    min_samples_split = f1_tree_0830['min_samples_split'],
    min_samples_leaf =f1_tree_0830['min_samples_leaf'] ,
    max_features = f1_tree_0830['max_features'],
    bootstrap = f1_tree_0830['bootstrap'],
    
)
# 모델 학습
model_rf_f1.fit(X_train, y_train)
# 예측
y_pred_rf = model_rf_f1.predict(X_test)

# 정확도 및 F1 점수 계산
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print(f"rf Accuracy: {accuracy_rf}")
print(f1_score(y_test, y_pred_rf, average='binary'))
pred_rf = model_rf_f1.predict(X_test.fillna(0))
get_clf_eval(y_test, pred_rf)
# 예측에 필요한 데이터 분리
x_test = test.drop(["target"], axis=1)
test_pred_rf = model_rf_f1.predict(x_test.drop(['Set ID'],axis = 1))
# sum(test_pred) # True로 예측된 개수
print(np.unique(test_pred_rf,return_counts = True))
test_pred_labels_rf = np.where(test_pred_rf == 1, 'AbNormal', 'Normal')
print(np.unique(test_pred_labels_rf,return_counts = True))
print(np.unique(test_pred_labels_rf[test_index_0],return_counts = True))
#제출 데이터 읽어오기 (df_test는 전처리된 데이터가 저장됨)
df_sub_rf_f1 = pd.read_csv("submission.csv")
df_sub_rf_f1["target"] = test_pred_labels_rf
df_sub_rf_f1.loc[test_index_0 , 'target'] = 'AbNormal'
# df_sub.loc[test_index_1 , 'target'] = test_pred_labels
print(np.unique(df_sub_rf_f1['target'],return_counts = True))
print(np.unique(df_sub_rf_f1['target'],return_counts = True)[1][0]/np.unique(df_sub_rf_f1['target'],return_counts = True)[1][1])
index = [181,498,679,1510,1739,3055, 3687, 4618, 5311, 5702, 5886, 7075, 8354, 8414, 8898, 9043, 10188, 10191, 10345, 10424,10948, 14807, 15456, 16876]
print(np.unique(df_sub_rf_f1.loc[index, 'target'],return_counts= True))
df_sub_rf_f1.loc[index,'target'] = 'AbNormal'
print(np.unique(df_sub_rf_f1['target'],return_counts = True))



xgb pre
XGBoost Accuracy: 0.932698255598169
0.13650793650793652
오차행렬:
 [[7496  146]
 [ 398   43]]

정확도: 0.9327
정밀도: 0.2275
재현율: 0.0975
F1: 0.1365
(array([0, 1]), array([16917,   444]))
(array(['AbNormal', 'Normal'], dtype='<U8'), array([  444, 16917]))
(array(['AbNormal', 'Normal'], dtype='<U8'), array([ 6, 22]))
(array(['AbNormal', 'Normal'], dtype=object), array([  466, 16895]))
0.02758212488902042
(array(['AbNormal', 'Normal'], dtype=object), array([21,  3]))
(array(['AbNormal', 'Normal'], dtype=object), array([  469, 16892]))

xgb f1
XGBoost Accuracy: 0.8641593467771866
0.21120689655172414
오차행렬:
 [[6838  804]
 [ 294  147]]

정확도: 0.8642
정밀도: 0.1546
재현율: 0.3333
F1: 0.2112
(array([0, 1]), array([15168,  2193]))
(array(['AbNormal', 'Normal'], dtype='<U8'), array([ 2193, 15168]))
(array(['AbNormal', 'Normal'], dtype='<U8'), array([ 9, 19]))
(array(['AbNormal', 'Normal'], dtype=object), array([ 2212, 15149]))
0.14601623869562347
(array(['AbNormal', 'Normal'], dtype=object), array([21,  

CatBoost Accuracy: 0.929852777434121
0.14736842105263157
오차행렬:
 [[7467  175]
 [ 392   49]]

정확도: 0.9299
정밀도: 0.2188
재현율: 0.1111
F1: 0.1474
(array([0, 1]), array([16849,   512]))
(array(['AbNormal', 'Normal'], dtype='<U8'), array([  512, 16849]))
(array(['AbNormal', 'Normal'], dtype='<U8'), array([ 6, 22]))
(array(['AbNormal', 'Normal'], dtype=object), array([  534, 16827]))
0.03173471206988768
(array(['AbNormal', 'Normal'], dtype=object), array([20,  4]))
(array(['AbNormal', 'Normal'], dtype=object), array([  538, 16823]))

ext f1 ver1
extratree Accuracy: 0.8448595818384264
0.20632911392405065
오차행렬:
 [[6666  976]
 [ 278  163]]

정확도: 0.8449
정밀도: 0.1431
재현율: 0.3696
F1: 0.2063
(array([0, 1]), array([14763,  2598]))
(array(['AbNormal', 'Normal'], dtype='<U8'), array([ 2598, 14763]))
(array(['AbNormal', 'Normal'], dtype='<U8'), array([10, 18]))
(array(['AbNormal', 'Normal'], dtype=object), array([ 2616, 14745]))
0.17741607324516787
(array(['AbNormal', 'Normal'], dtype=object), array([21,  3

### 보팅

In [6]:
from sklearn.ensemble import VotingClassifier

weights = []

# 앙상블을 위한 분류기 리스트 생성
classifiers = [
#     ('lgbm', model_lgbm),
    ('xgb_pre', model_xgb_pre),
    ('xgb_f1', model_xgb_f1),
#         ('xgb_pre', model_xgb_pre),
    ('lgbm_f1', model_lgbm_f1),
        ('cat_pre', model_catboost_pre),
    ('cat_f1', model_catboost_f1),
    ('extratree_pre',model_extratree_pre),
    ('extratree_f1',model_extratree_f1),
       ('extratree_pre_ver2',model_extratree_pre_ver2),
    ('extratree_f1_ver2',model_extratree_f1_ver2),
    
     ('rf_pre',model_rf_pre),
    ('rf_f1',model_rf_f1),

#     ('catboost', model_catboost),
#     ('decisiontree',model_dt)
]

# 소프트 투표 기반의 앙상블 모델 생성
ensemble_model = VotingClassifier(estimators=classifiers, voting='hard')

# 앙상블 모델 학습
ensemble_model.fit(X_train, y_train)
# 예측
y_pred_ensemble = ensemble_model.predict(X_test)

# 정확도 및 F1 점수 계산
accuracy_ensemble = accuracy_score(y_test, y_pred_ensemble)
print(f"voting Accuracy: {accuracy_ensemble}")
print(f1_score(y_test, y_pred_ensemble, average='binary'))
pred_ensem = ensemble_model.predict(X_test.fillna(0))
get_clf_eval(y_test, pred_ensem)
# 예측에 필요한 데이터 분리
x_test = test.drop(["target"], axis=1)
test_pred_ensemble = ensemble_model.predict(x_test.drop(['Set ID'],axis = 1))
# sum(test_pred) # True로 예측된 개수
print(np.unique(test_pred_ensemble,return_counts = True))
test_pred_labels_ensemble = np.where(test_pred_ensemble == 1, 'AbNormal', 'Normal')
print(np.unique(test_pred_labels_ensemble,return_counts = True))
print(np.unique(test_pred_labels_ensemble[test_index_0],return_counts = True))
#제출 데이터 읽어오기 (df_test는 전처리된 데이터가 저장됨)
df_sub_ens4  = pd.read_csv("submission.csv")
df_sub_ens4["target"] = test_pred_labels_ensemble
df_sub_ens4.loc[test_index_0 , 'target'] = 'AbNormal'
# df_sub.loc[test_index_1 , 'target'] = test_pred_labels
print(np.unique(df_sub_ens4['target'],return_counts = True))
print(np.unique(df_sub_ens4['target'],return_counts = True)[1][0]/np.unique(df_sub_ens4['target'],return_counts = True)[1][1])
index = [181,498,679,1510,1739,3055, 3687, 4618, 5311, 5702, 5886, 7075, 8354, 8414, 8898, 9043, 10188, 10191, 10345, 10424,10948, 14807, 15456, 16876]
print(np.unique(df_sub_ens4.loc[index, 'target'],return_counts= True))
df_sub_ens4.loc[index,'target'] = 'AbNormal'
print(np.unique(df_sub_ens4.loc[index, 'target'],return_counts= True))
print(np.unique(df_sub_ens4['target'],return_counts = True))

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 1816, number of negative: 30514
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.006074 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2378
[LightGBM] [Info] Number of data points in the train set: 32330, number of used features: 116
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.056171 -> initscore=-2.821549
[LightGBM] [Info] Start training from score -2.821549
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, bes